// ─── Sacyr IRL Forms Data ─────────────────────────────────────────────────────
// 15 cargo-specific IRL forms exclusively for Sacyr
// Company ID: 3024ab6f-8b7f-4735-992e-f6442d26b09b

export const SACYR_COMPANY_ID = "3024ab6f-8b7f-4735-992e-f6442d26b09b";

export interface SacyrIrlPregunta {
  pregunta: string;
  opciones: string[];
  correcta: number; // 0-based index
}

export interface SacyrIrlFormData {
  slug: string;
  cargo_name: string;
  area: string;
  descripcion_puesto: string;
  tareas: string[];
  lugares_trabajo: string[];
  herramientas: string[];
  orden_aseo: string[];
  preguntas: SacyrIrlPregunta[];
}

// ─── Shared quiz questions (same for all 15 forms) ────────────────────────────
export const SACYR_IRL_PREGUNTAS: SacyrIrlPregunta[] = [
  {
    pregunta: "¿Cuál de las siguientes contingencias son cubiertas por la ley 16.744?",
    opciones: [
      "Accidentes en el trayecto directo, de ida o regreso, entre la habitación y el lugar de trabajo.",
      "Accidentes a causa con ocasión del trabajo, y que le produzcan incapacidad o muerte.",
      "Enfermedades Profesionales causadas por el ejercicio de la profesión.",
      "Todas las anteriores son correctas.",
    ],
    correcta: 3,
  },
  {
    pregunta: "¿Cuál de las siguientes alternativas corresponde a la definición: \"Es la declaración escrita de los compromisos y principios valóricos por parte de la Alta Dirección\"?",
    opciones: [
      "Inducción de Informar los riesgos laborales.",
      "Políticas de SST, Prevención de Alcohol, Tabaco y Drogas, Diversidad e Inclusión, Seguridad Vial.",
      "Matriz de Identificación de Peligros y Evaluación de Riesgos.",
      "Ninguna de las anteriores es correcta.",
    ],
    correcta: 1,
  },
  {
    pregunta: "Si usted sufre una lesión física mientras realiza labores en la empresa y esta provoca incapacidad para continuar con sus labores, esta definición corresponde a:",
    opciones: [
      "Accidente Común.",
      "Accidente del Trabajo.",
      "Accidente de Trayecto.",
      "Enfermedad Profesional.",
    ],
    correcta: 1,
  },
  {
    pregunta: "Respecto a la pregunta anterior, si su lesión es menor y no le provoca incapacidad para seguir con sus labores, ¿qué es lo que usted debe hacer?",
    opciones: [
      "Esperar que la lesión provoque mayor dolencia para luego informar.",
      "Informar inmediatamente a supervisor y/o personal de SST, antes del término del turno.",
      "Dirigirse a urgencia sin informar a supervisor y/o personal de SST.",
      "Las Alternativas a) y c) son correctas.",
    ],
    correcta: 1,
  },
  {
    pregunta: "El Equipo de Protección Personal, cada vez que realice labores, usted debe:",
    opciones: [
      "Revisar que se encuentren en estado óptimo para ser utilizado.",
      "Utilizar obligatoriamente.",
      "No se podrán prestar entre compañeros.",
      "Todas las anteriores son correctas.",
    ],
    correcta: 3,
  },
  {
    pregunta: "¿Cuál de las siguientes alternativas son medidas preventivas frente a altas temperaturas?",
    opciones: [
      "Consumir frutas y verduras, evitando la ingesta de alimentos grasos.",
      "Beber líquidos constantemente, aunque no sienta sed; priorizando el consumo de agua, evitando las bebidas alcohólicas y azucaradas.",
      "Participar en actividades formativas de exposición sobre los riesgos asociados a trabajar en altas temperaturas.",
      "Todas las alternativas son correctas.",
    ],
    correcta: 3,
  },
  {
    pregunta: "Si detecta fuego recién iniciado en su centro de trabajo, usted debe:",
    opciones: [
      "Solo si está capacitado tratar de apagar con extintor PQS o CO2 según el tipo de fuego.",
      "Si no pudo controlar fuego evacuar hacia zona de seguridad del centro y avisar a bomberos y a encargado del centro.",
      "Salir corriendo y gritando hacia la calle y no avisar a nadie.",
      "Alternativas a) y b) son correctas.",
    ],
    correcta: 3,
  },
  {
    pregunta: "¿Cuál de las siguientes políticas indica en su descripción: \"Todas aquellas características que hacen de cada persona un ser único\"?",
    opciones: [
      "Política de Seguridad y Salud del Trabajo.",
      "Política de Prevención para el Alcohol, Tabaco y Drogas en el trabajo.",
      "Política de Inclusión y Diversidad.",
      "Política de Seguridad Vial.",
    ],
    correcta: 2,
  },
];

// ─── Helper: split concatenated list text into array items ────────────────────
function splitList(raw: string): string[] {
  if (!raw || raw.trim() === "No aplica.") return [];
  // Split at boundaries: end-of-sentence followed by capital, or explicit newline
  return raw
    .split(/(?<=[.;])\s*(?=[A-ZÁÉÍÓÚ])|(?<=[a-záéíóúñ])\s*(?=[A-ZÁÉÍÓÚ][a-záéíóúñ])|[\n]/)
    .map(s => s.trim())
    .filter(s => s.length > 2);
}

// ─── The 15 forms ─────────────────────────────────────────────────────────────
export const SACYR_IRL_FORMS: SacyrIrlFormData[] = [
  {
    slug: "administrador_de_contrato",
    cargo_name: "Administrador de Contrato",
    area: "Edificación",
    descripcion_puesto: "Es el encargado de gestionar los aspectos contractuales de un proyecto de construcción desde su inicio hasta su finalización. Su labor es coordinar la redacción, negociación, ejecución y seguimiento de contratos, asegurando que se cumplan los términos acordados y se minimicen los riesgos legales y financieros.",
    tareas: [
      "Revisar contratos de construcción, subcontratos, órdenes de compra, y documentos relacionados con el proyecto, asegurando su claridad, precisión y cumplimiento con las leyes y regulaciones aplicables.",
      "Supervisar la ejecución de los contratos, verificando el cumplimiento de los plazos, costos, especificaciones técnicas y demás términos acordados.",
      "Tramitar cambios en el alcance del proyecto, ampliaciones de plazo y gestionar reclamaciones o disputas contractuales.",
      "Asegurar que las actividades de construcción se realicen conforme a los estándares de calidad y seguridad establecidos en los contratos y la normativa vigente.",
      "Identificar y evaluar los riesgos contractuales y financieros asociados al proyecto, proponiendo medidas para mitigarlos.",
    ],
    lugares_trabajo: [
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
    ],
    herramientas: [],
    orden_aseo: [],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "ayudante",
    cargo_name: "Ayudante de Especialidades",
    area: "Edificación",
    descripcion_puesto: "El ayudante realiza diversas tareas de apoyo, cargar y/o transportar materiales, mantener el área limpia y orden a distintas especialidades que se ejecutan en una obra.",
    tareas: [
      "Realizar levantamiento de cargas pesadas.",
      "Realizar labores de aseo en distintos lugares de la obra.",
      "Levantar, transportar y almacenar diversos materiales, como madera, ductos, cables, fierro, moldajes, escalerillas, etc.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja sobre plataformas, escalas y andamios.",
      "A nivel del terreno, en colocación de elementos diversos.",
      "A nivel de terreno, en transporte y almacenamiento de diversos materiales.",
    ],
    herramientas: [
      "Alicate", "Carretilla", "Transpaleta", "Destornillador", "Mazo",
      "Sierra manual", "Tijeras", "Terraja de roscar", "Cincel", "Corta cartón",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "capataz",
    cargo_name: "Capataz",
    area: "Edificación",
    descripcion_puesto: "El capataz es el jefe de una especialidad en particular. Debe administrar los recursos y el grupo de trabajo que se le ha asignado (maestros, ayudantes, jornales, subcontratistas, etc.), para lograr los resultados esperados en plazos, costos, calidad y seguridad.",
    tareas: [
      "Planificar y controlar el uso de materiales, herramientas, maquinaria y equipos de su especialidad.",
      "Supervisar en terreno las distintas faenas de su especialidad.",
      "Dirigir y controlar al personal de su especialidad.",
      "Instruir al personal a su cargo en cómo realizar las distintas tareas.",
      "Identificar y controlar riesgos en los frentes de trabajo.",
    ],
    lugares_trabajo: [
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
      "En altura sobre andamios, plataformas, pasarelas o losas.",
      "En trabajos nocturnos puede tener bajos niveles de iluminación.",
    ],
    herramientas: [
      "Debe conocer las distintas herramientas de su especialidad.",
      "Debe conocer el funcionamiento de los distintos equipos o maquinarias que se utilizan en su especialidad.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "carpintero_obra_civiles",
    cargo_name: "Carpintero Obra Civiles",
    area: "Edificación",
    descripcion_puesto: "El carpintero de obra gruesa realiza tareas relacionadas con preparación y colocación de moldajes de distinto tipo, sean estos de madera o industrializados. Además, prepara y monta andamios y carreras para hormigonar, construye mesones de trabajo, escalas, caballetes, construye envigados, pisos, tabiques, cielos y techumbres, colocando los revestimientos que correspondan.",
    tareas: [
      "Saca niveles y realiza trazados de elementos geométricos complejos.",
      "Realiza levantamiento de cargas.",
      "Prepara, coloca y descimbra moldajes de todo tipo, de madera o industrializados.",
      "Coloca marcos de madera y metálicos.",
      "Ejecuta entramados de madera para estructuras de pisos o tabiques.",
      "Construye andamios.",
      "Construye cerchas y todo tipo de techumbres.",
      "Prepara y coloca revestimientos de pisos, cielos y muros.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja sobre plataformas, escalas y andamios.",
      "A nivel del terreno, en colocación de elementos diversos.",
      "En altura en la construcción de cielos, techumbres y colocación de moldajes exteriores.",
      "Entorno de enfierradores.",
    ],
    herramientas: [
      "Huincha, plomo, tizador, escuadras, nivel de mano.",
      "Martillos, serruchos, alicates, llaves de punta.",
      "Chuzo, carretillas, botadores, prensas metálicas, sargentos.",
      "Formones, cepillo, escofinas, limas, atornilladores.",
      "Sierra circular, taladro, caladora, esmeril angular.",
      "Banco de sierra circular.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "carpintero_og",
    cargo_name: "Carpintero Obra Gruesa (OG)",
    area: "Edificación",
    descripcion_puesto: "El carpintero de obra gruesa realiza tareas relacionadas con preparación y colocación de moldajes de distinto tipo, sean estos de madera o industrializados. Además, prepara y monta andamios y carreras para hormigonar, construye mesones de trabajo, escalas, caballetes, construye envigados, pisos, tabiques, cielos y techumbres, colocando los revestimientos que correspondan.",
    tareas: [
      "Saca niveles y realiza trazados de elementos geométricos complejos.",
      "Realiza levantamiento de cargas.",
      "Prepara, coloca y descimbra moldajes de todo tipo, de madera o industrializados.",
      "Coloca marcos de madera y metálicos.",
      "Ejecuta entramados de madera para estructuras de pisos o tabiques.",
      "Construye andamios.",
      "Construye cerchas y todo tipo de techumbres.",
      "Prepara y coloca revestimientos de pisos, cielos y muros.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja sobre plataformas, escalas y andamios.",
      "A nivel del terreno, en colocación de elementos diversos.",
      "En altura en la construcción de cielos, techumbres y colocación de moldajes exteriores.",
    ],
    herramientas: [
      "Huincha, plomo, tizador, escuadras, nivel de mano.",
      "Martillos, serruchos, alicates, llaves de punta.",
      "Chuzo, carretillas, botadores, prensas metálicas, sargentos.",
      "Formones, cepillo, escofinas, limas, atornilladores.",
      "Sierra circular, taladro, caladora, esmeril angular.",
      "Banco de sierra circular.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "carpintero_terminaciones",
    cargo_name: "Carpintero Terminaciones",
    area: "Edificación",
    descripcion_puesto: "El carpintero de Terminaciones realiza tareas relacionadas con preparación, colocación y tratamiento de materiales de distinto tipo, ya sean en bruto, elaboradas o planchas de vulcanita, con el fin de ejecutar todo tipo de terminaciones de una obra.",
    tareas: [
      "Saca niveles y realiza trazados de elementos geométricos complejos.",
      "Realiza movimientos repetitivos y levantamientos de cargas.",
      "Coloca puertas, ventanas, mamparas, persianas, etc.",
      "Coloca todo tipo de quincallería, chapas, picaportes, españoletas, bisagras, etc.",
      "Coloca marcos de madera y metálicos.",
      "Montaje y desmontaje de andamios.",
      "Ejecuta toda clase de terminaciones interiores o exteriores en madera, como colocación de cubrejuntas, cornisas, pilastras, guardapolvos, tapacanes, etc.",
      "Coloca revestimientos especiales: terciado, vulcanitas, aislantes, etc.",
      "Traza y construye.",
      "Realiza terminaciones con pintura o barnices en madera.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja sobre plataformas, escalas y andamios.",
      "A nivel del terreno, en colocación de elementos diversos.",
      "En altura, en el montaje de cielos, colocación de cornisas o terminaciones.",
    ],
    herramientas: [
      "Huincha, plomo, tizador, escuadras, nivel de mano.",
      "Martillos, serruchos, alicates, destornilladores, llaves de punta.",
      "Formones, cepillo, escofinas, limas, atornilladores, prensas, cuchillo cartonero.",
      "Sierra circular, taladro, caladora, esmeril angular.",
      "Tronzadora, cepilladora eléctrica, caladora tupi portátil.",
      "Banco de sierra circular, lijadora rotatoria o de banda.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "electricista",
    cargo_name: "Electricista",
    area: "Edificación",
    descripcion_puesto: "El electricista ejecuta todo tipo de instalaciones eléctricas, de alumbrado o fuerza y realización de su mantención.",
    tareas: [
      "Realiza instalaciones eléctricas provisorias y definitivas.",
      "Ejecuta instalaciones de alumbrado.",
      "Ejecuta instalaciones de fuerza: motores monofásicos, trifásicos, motobombas y moto generadores.",
      "Construye mallas de tierra y efectúa su medición posterior.",
      "Traza y ejecuta canalizaciones aéreas y subterráneas.",
      "Prepara, hace hilos y coloca tuberías o cañerías galvanizadas para recibir conductores.",
      "Perfora todo tipo de materiales para embutir canalizaciones.",
      "Prepara tuberías plásticas, corta, pule, curva con calor y pega.",
      "Alambra canalizaciones y conecta tableros de control.",
      "Realiza montaje de escalerillas y bandejas porta conductores.",
      "Soldar todo tipo de terminales para conductores.",
      "Levanta y transporta materiales.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja a nivel del terreno en la instalación de canalizaciones subterráneas y mallas de tierra.",
      "Trabaja a nivel de terreno en la instalación de la canalización, alambrado y montaje de tableros.",
      "En altura en el montaje y mantención de líneas aéreas e instalación de escalerillas.",
      "Circula por toda la obra, por escalas, plataformas y andamios.",
    ],
    herramientas: [
      "Combos, puntos, cinceles.",
      "Alicates, destornilladores, pelacables, cuchillos.",
      "Limas, sierra, brocas, sierras copa.",
      "Terrajas.",
      "Prensas cadena.",
      "Esmeril angular, taladro, caladoras.",
      "Soplete a gas.",
      "Cautín eléctrico.",
      "Instrumentos para medir voltaje, intensidad de corriente, potencia, etc.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "enfierrador",
    cargo_name: "Enfierrador",
    area: "Edificación",
    descripcion_puesto: "El enfierrador realiza tareas relacionadas con preparación y colocación de fierro de construcción en estructuras de hormigón armado.",
    tareas: [
      "Hace plantillas de doblado de fierro.",
      "Estira y corta fierro en rollos.",
      "Levanta, transporta y coloca paquetes de fierro.",
      "Realiza trazados de distribución de fierro.",
      "Prepara y coloca fierro de distinto diámetro.",
      "Estira, dobla, corta, grifa, coloca y amarra todo tipo de fierro.",
      "Prepara y coloca fierro para distintos tipos de elementos: fundaciones, pilares, vigas, losas y muros.",
    ],
    lugares_trabajo: [
      "En general trabaja en etapa de obra gruesa, llevando el ritmo de avance de la obra.",
      "Realiza labores en el exterior e interior.",
      "Trabaja sobre andamios, plataformas para armar muros.",
      "A nivel de terreno o de losa, en armado de radieres o losas.",
      "En altura, en el armado de pilares.",
      "Trabaja en bancos de trabajo en talleres donde se mantiene el acopio de fierro.",
    ],
    herramientas: [
      "Huincha, alicate, alambre.",
      "Grifas industriales y construidas en obra.",
      "Esmeril angular.",
      "Cortadora y dobladora eléctrica.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "equipo_de_topografia",
    cargo_name: "Equipo de Topografía (Trazador / Geomensor / Topógrafo)",
    area: "Edificación",
    descripcion_puesto: "Geomensor, Nivelador, Topógrafo: es el encargado de replantear en terreno los distintos elementos que se construirán, así como dar los niveles correspondientes de los elementos.",
    tareas: [
      "Transporta e instala instrumentos de medición.",
      "Saca niveles y traslada cotas con nivel óptico.",
      "Traza ejes con taquímetro de elementos estructurales o soleras, calzadas y urbanización en general.",
      "Replantea y traza excavaciones para fundaciones de distinto tipo.",
      "Da plomos, líneas, niveles, ejes y puntos de partida para cada una de las operaciones que se van iniciando.",
      "Traza shaft, escotillas, ascensores, ductos, etc.",
      "Da niveles de losas, pilares y chequea durante la faena de hormigonado.",
    ],
    lugares_trabajo: [
      "Trabaja en interior y exterior.",
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
      "En altura sobre andamios, pasarelas o losas.",
      "En trabajos nocturnos puede tener bajos niveles de iluminación.",
    ],
    herramientas: [
      "Nivel óptico.",
      "Taquímetro.",
      "Mira topográfica.",
      "Huinchas de diferentes longitudes.",
      "Combos y estacas de madera.",
      "Cal, marcadores y tizador.",
    ],
    orden_aseo: [
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "guardia",
    cargo_name: "Guardia de Seguridad",
    area: "Edificación",
    descripcion_puesto: "El guardia efectúa la vigilancia en áreas internas y externas de las instalaciones para preservar la seguridad del recurso humano y económico de la obra, instalaciones, mobiliario, equipos y utensilios, así como para mantener el orden y tranquilidad en todas las áreas.",
    tareas: [
      "Se preocupa de la vigilancia y seguridad en las instalaciones.",
      "Realiza el control del ingreso y retiro del personal.",
      "Vigila la instalación para impedir la entrada ilícita, evita robos, incendios y otros riesgos.",
      "Verifica y registra cualquier situación anormal que ocurra en las instalaciones.",
      "En caso de activación de alarmas debe llamar a carabineros.",
      "Eventualmente cumple funciones de portero verificando la entrada y salida del personal, proveedores y visitantes, controlando pérdidas y robos.",
      "Atiende las solicitudes de información en general y se preocupa de entregar una respuesta satisfactoria.",
      "Presta la ayuda necesaria para asegurar que el estacionamiento de automóviles se realice en condiciones de seguridad.",
    ],
    lugares_trabajo: [
      "Exterior e interior de la obra.",
      "Estacionamiento.",
      "Casetas de vigilancia.",
    ],
    herramientas: [
      "Equipo de radio transmisor portátil, linterna, alarmas, central de alarmas.",
      "Circuito cerrado de televisión, cámaras de vigilancia.",
    ],
    orden_aseo: [
      "Mantener las áreas de trabajo limpias y caseta de vigilancia.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "jefe_de_terreno",
    cargo_name: "Jefe de Terreno",
    area: "Edificación",
    descripcion_puesto: "El Jefe de Terreno es el encargado de planificar, programar y controlar el avance físico de la obra en el corto y mediano plazo. Deberá dar cumplimiento a las normas y estándares asociados a calidad, medio ambiente y seguridad.",
    tareas: [
      "Participar de la planificación general del proyecto.",
      "Estudiar y conocer en detalle los documentos relacionados con el proyecto: especificaciones técnicas, planos, bases administrativas.",
      "Establecer relación con el Mandante, de manera de conocer y aplicar cualquier cambio en el proyecto.",
      "Determinar la necesidad de recursos materiales y humanos para la ejecución de las actividades.",
      "Generar planificaciones de trabajo para su línea de supervisión a cargo.",
      "Solicitar materiales.",
      "Evaluar y controlar el avance físico de cada una de las partidas y sus plazos de ejecución.",
      "Coordinar las tareas de los subcontratos.",
      "Revisar y controlar la calidad de las actividades realizadas en obra.",
      "Revisar y controlar la aplicación efectiva de los procedimientos constructivos.",
      "Aplicar el Plan de Prevención de Riesgos de la Obra.",
    ],
    lugares_trabajo: [
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
    ],
    herramientas: [
      "Debe conocer el funcionamiento de los distintos equipos o maquinarias que se utilizan en la Obra.",
    ],
    orden_aseo: [],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "maestro_de_instalaciones",
    cargo_name: "Maestro de Instalaciones",
    area: "Edificación",
    descripcion_puesto: "El maestro de instalaciones es un personal calificado que se especializa en la instalación y mantenimiento de sistemas eléctricos, sanitarios, de climatización o de otro tipo en edificios o infraestructuras.",
    tareas: [
      "Interpreta planos de instalaciones para ejecutar en base al diseño y requerimientos técnicos de cada sistema.",
      "Ejecuta el montaje de las instalaciones específicas.",
      "Perforar e instala todo tipo de materiales y equipos.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja a nivel de terreno en la instalación de cañerías, tuberías, artefactos o preparación de material en el taller.",
      "En altura en el montaje de las instalaciones, ductos, cañerías, tuberías, trapecio, suportación.",
      "Circula por toda la obra, por escalas, pasarelas, andamios, etc., para desplazarse a su frente de trabajo.",
    ],
    herramientas: [
      "Combo, cinceles, puntos.",
      "Huincha, plomo, nivel.",
      "Alicates, destornilladores, cuchillos.",
      "Limas, sierra, brocas, escobilla de acero.",
      "Esmeril angular, taladro.",
      "Soplete a gas.",
      "Termofusión.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura, incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "monitor_de_seguridad",
    cargo_name: "Monitor de Seguridad",
    area: "Edificación",
    descripcion_puesto: "El monitor es la persona encargada de monitorear y prevenir los principales factores de riesgos laborales en el área de trabajo, promoviendo una cultura de seguridad y salud en el trabajo.",
    tareas: [
      "Implementación y realización de Vervic, dirigidas hacia el personal de Sacyr y empresas colaboradoras.",
      "Control diario de documentación en plataforma SMART.",
      "Control documental de las charlas de inducción IRL.",
      "Instalación y reposición de señalética.",
      "Monitorear conductas de los trabajadores y retroalimentación.",
    ],
    lugares_trabajo: [
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
    ],
    herramientas: [
      "Atornillador.",
      "Engrapadora.",
    ],
    orden_aseo: [
      "Mantener su área de trabajo limpia y ordenada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "operador_de_maquinaria_pesada",
    cargo_name: "Operador de Maquinaria Pesada",
    area: "Edificación",
    descripcion_puesto: "El operador de maquinaria pesada es el responsable de la operación y mantención básica del equipo. Cada equipo posee características propias que lo hacen distinto del resto.",
    tareas: [
      "Pone en funcionamiento, opera y realiza la mantención básica de su máquina.",
      "Dependiendo de la función que desempeña cada equipo, realiza cortes, cordones, escarifica, mezcla, nivela, extiende, carga, compacta y transporta distintos tipos de suelo, para la construcción o conservación de caminos.",
      "Arrastra a otros equipos.",
      "Realiza movimientos repetitivos con los brazos.",
    ],
    lugares_trabajo: [
      "Realiza su labor en la cabina del equipo.",
      "Puede laborar en turnos.",
      "Trabajos en pendiente, sobre terraplenes.",
      "Trabajo en diversas condiciones climáticas.",
      "Ambiente con polvo.",
    ],
    herramientas: [
      "Herramientas usadas en la mantención mecánica.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener las vías de tránsito libres de obstáculos.",
      "Mantener las áreas de trabajos segregadas, delimitadas y señalizadas.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "operador_gt",
    cargo_name: "Operador de Grúa Torre (GT)",
    area: "Edificación",
    descripcion_puesto: "El operador de Grúa Torre debe ser un trabajador capacitado, entrenado y autorizado en el uso de este equipo, destinado a realizar trabajos de levantamiento y transporte de cargas en la obra.",
    tareas: [
      "Realiza trabajos al interior.",
      "En altura física.",
      "En ambientes nocivos y ruidosos.",
    ],
    lugares_trabajo: [
      "Grúa torres empotradas.",
      "Grúas torres con lastre basal.",
      "Gancho simple y doble ramal.",
      "Eslingas de cadenas, estrobos, cabos, eslingas de poliéster.",
    ],
    herramientas: [
      "Combo, martillo cincelador, huincha, escuadra, plomo, nivel.",
      "Alicate, tenazas, caimán, destornilladores.",
      "Limas, brocas, prensas, tornillos mecánicos.",
      "Esmeril angular, taladro, sierra axial.",
      "Máquina de soldar.",
      "Equipo de oxiacetileno.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura, incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },

  // ── 9 nuevos formularios (contenido fiel a los documentos originales) ─────
  {
    slug: "operador_montacargas",
    cargo_name: "Operador de Montacargas",
    area: "Edificación",
    descripcion_puesto: "El operador será una persona debidamente capacitada en la correcta operación segura del equipo, además será instruido técnicamente sobre el funcionamiento, sistemas de seguridad, mantención e inspección básica y aplicando las recomendaciones establecidas en los procedimientos y manuales aplicables a este equipo.",
    tareas: [
      "A diario realizará una inspección del equipo de acuerdo a lo indicado en el Procedimiento Operación Segura.",
      "Cada día verificará la tabla de carga y de distribución de materiales, esto le permitirá cargar el montacargas minimizando el riesgo de sobreesfuerzo y desestabilizar del equipo.",
      "Mantendrá informado al profesional a cargo del equipo, de toda anormalidad que le indique una posible falla.",
      "Realizará movimientos repetitivos en el traslado de materiales desde y hacia el interior del equipo.",
      "Trasladará materiales hacia los distintos niveles de edificación.",
      "Apoyará en el retiro de escombro desde los centros de acopio y hacia los lugares de contención provisoria.",
      "Manipulará los bloqueos existentes en cada nivel de la edificación, permitiendo la entrada y salida del equipo.",
      "Manipulará los tableros y botoneras energizadas para activar, desactivar y bloquear el equipo.",
      "Manipulará equipo de comunicación radial, informando su posición o reportando observaciones.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior del equipo.",
      "Trabaja en los distintos niveles de edificación en el recorrido habitual y vertical en el traslado de materiales, escombros o personas.",
      "Circula por toda la obra.",
    ],
    herramientas: [
      "Montacargas.",
      "Ascensor de cremallera.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantendrá o exigirá su equipo aseado y ordenado como también los accesos a los distintos niveles.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "personal_de_aseo",
    cargo_name: "Personal de Aseo",
    area: "Edificación",
    descripcion_puesto: "Efectúa labores de aseo y limpieza en oficinas, baños, comedores, pasillos, patios, bodega y, en general, todas las áreas de la obra.",
    tareas: [
      "Mantener limpias las áreas administrativas y de uso público.",
      "Lavar pisos y mantener limpios y desinfectados los baños públicos.",
      "Mantener el stock de elementos normalmente utilizados en los baños (papel higiénico, jabón) y en sus labores de limpieza según instrucciones asignadas.",
      "Efectúa diversas tareas de ordenamiento en las distintas dependencias.",
      "Levantar, transportar y almacenar diversos materiales, tales como los artículos de aseo.",
      "Limpiar las áreas de pasillos, escaleras y en general, todas las áreas.",
      "Retirar y trasladar basura desde las diferentes áreas al sector de acopio de basura orgánica.",
    ],
    lugares_trabajo: [
      "Realiza sus labores en las distintas áreas que conforman la instalación o edificio, tanto en interiores como en exteriores.",
    ],
    herramientas: [
      "Escobillones, escobilla, escoba, mopas, otros.",
      "Paños, baldes, otros.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "prevencionista_de_riesgos",
    cargo_name: "Prevencionista de Riesgos",
    area: "Edificación",
    descripcion_puesto: "El Prevencionista de Riesgos es el encargado de identificar, evaluar y controlar los riesgos laborales para prevenir accidentes y enfermedades profesionales.",
    tareas: [
      "Identificación y evaluación de riesgos, analizando los puestos de trabajo, procesos y condiciones para identificar peligros potenciales, evaluando su probabilidad e impacto.",
      "Diseño e implementación de programas de prevención, planes de seguridad, protocolos Minsal, protocolos de actuación y medidas de control para eliminar o minimizar los riesgos identificados.",
      "Capacitación y sensibilización, formación a los trabajadores sobre los riesgos laborales, medidas preventivas y el uso correcto de equipos de protección personal (EPP).",
      "Realiza inspecciones periódicas y auditorias para verificar el cumplimiento de las normas de seguridad y detectar posibles fallos en la implementación de las medidas preventivas.",
      "Investiga las causas de los accidentes laborales para implementar medidas correctivas y evitar que se repitan.",
      "Desarrolla planes de emergencia y coordina la respuesta ante situaciones de riesgos como incendios o evacuaciones.",
    ],
    lugares_trabajo: [
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
    ],
    herramientas: [
      "Debe conocer el funcionamiento de los distintos equipos o maquinarias que se utilizan en la Obra.",
    ],
    orden_aseo: [],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "profesional",
    cargo_name: "Profesional",
    area: "Edificación",
    descripcion_puesto: "Un profesional de terreno, en el contexto de la construcción u obras, es la persona encargada de supervisar y coordinar las actividades diarias en el sitio de trabajo. Su función principal es asegurar que la obra se ejecute conforme a los planos, especificaciones técnicas, dentro de los plazos y presupuestos establecidos. Además, debe velar por la seguridad y el cumplimiento de las normativas vigentes.",
    tareas: [
      "Participar de la planificación general del proyecto.",
      "Estudiar y conocer en detalle los documentos relacionados con el proyecto: especificaciones técnicas, planos, bases administrativas.",
      "Establecer relación con el Mandante, de manera de conocer y aplicar cualquier cambio en el proyecto que ellos soliciten.",
      "Determinar la necesidad de recursos materiales y humanos para la ejecución de las actividades.",
      "Generar planificaciones de trabajo para su línea de supervisión a cargo.",
      "Evaluar y controlar el avance físico de cada una de las partidas y sus plazos de ejecución con relación al programa de la obra.",
      "Coordinar las tareas de las empresas colaboradoras.",
      "Evaluar a las empresas colaboradoras.",
      "Revisar y controlar la calidad de las actividades realizadas en obra.",
      "Revisar y controlar la aplicación efectiva de los procedimientos constructivos para anticiparse a posibles riesgos.",
      "Aplicar el Plan de Prevención de Riesgos de la Obra.",
    ],
    lugares_trabajo: [
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
    ],
    herramientas: [
      "Debe conocer el funcionamiento de los distintos equipos o maquinarias que se utilizan en la Obra.",
    ],
    orden_aseo: [],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "rigger_señalero",
    cargo_name: "Rigger - Señalero",
    area: "Edificación",
    descripcion_puesto: "El Rigger es la persona capacitada, entrenada y certificada para apoyar al operador de grúa torre, mediante señales o por radio transmisora durante la maniobra, es el encargado del estrobado de las cargas. El señalero indica las maniobras a maquinarias en movimiento en los puntos ciegos que tiene el operador desde la cabina, realiza tareas de control de tránsito cuando se realizan salida y entrada de camiones a la obra.",
    tareas: [
      "Como rigger, indica por código de señales al operador de maquinaria pesada o grúa torre, los movimientos que debe realizar, cuando este no tiene visibilidad del punto de trabajo.",
      "Como apoyo de las maniobras, se encarga del correcto estrobado y amarre de las cargas a izar.",
      "Como señalero, guía al operador de maquinaria en los puntos ciegos desde la cabina.",
      "Realiza control de tránsito en entradas y salidas de camiones a la obra.",
    ],
    lugares_trabajo: [
      "En general trabaja en etapa de obra gruesa, llevando el ritmo de avance de la obra.",
      "Realiza labores en el exterior e interior.",
      "Trabaja sobre andamios, plataformas para armar muros.",
      "A nivel de terreno o de losa, en armado de radieres o losas.",
      "En altura, en el armado de pilares.",
      "Trabaja en bancos de trabajo en talleres donde se mantiene el acopio de fierro.",
    ],
    herramientas: [
      "Huincha, alicate, alambre.",
      "Grifas industriales y construidas en obra.",
      "Esmeril angular.",
      "Cortadora y dobladora eléctrica.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "sanitario",
    cargo_name: "Instalador Sanitario",
    area: "Edificación",
    descripcion_puesto: "El instalador sanitario ejecuta todo tipo de instalaciones de agua potable y alcantarillado domiciliario, con distinto tipo de materiales.",
    tareas: [
      "Ejecuta y repara instalaciones de agua potable; coloca tuberías, cañerías y fitings.",
      "Ejecuta y repara instalaciones de alcantarillado; coloca tuberías, ejecuta cámaras de inspección o monta cámaras fabricadas.",
      "Instala y repara todo tipo de artefactos sanitarios y accesorios de artefactos.",
      "Instala y emboquilla tubos de cemento comprimido de distintas dimensiones.",
      "Efectúa pruebas de presión y hermeticidad de las instalaciones.",
      "Pica todo tipo de materiales para embutir tuberías.",
      "Prepara tuberías plásticas: corta, pule, curva con calor y pega.",
      "Prepara cañerías de cobre: corta, pule, monta y suelda.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja a nivel de terreno en la instalación de tuberías, artefactos o en el taller.",
      "Trabaja bajo nivel de terreno en la instalación de tuberías, tubos y construcción o remate de cámaras de inspección.",
      "En altura en el montaje y mantención de descargas, ventilaciones de alcantarillados o en el montaje de plantas de alcantarillado en losas de distintos pisos.",
      "Circula por toda la obra, por escalas, pasarelas, andamios, etc., para desplazarse a su frente de trabajo.",
    ],
    herramientas: [
      "Carretilla.",
      "Combo, cinceles, puntos.",
      "Huincha, plomo, nivel.",
      "Alicates, destornilladores, cuchillos.",
      "Limas, sierra, brocas, escobilla de acero.",
      "Esmeril angular, taladro.",
      "Soplete a gas.",
      "Instrumento de evaluación multi-gases.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "soldador",
    cargo_name: "Soldador",
    area: "Edificación",
    descripcion_puesto: "El soldador realiza tareas relacionadas con corte y unión de fierro, por medio de soldadura al arco u equipos de oxiacetileno.",
    tareas: [
      "Saca niveles y realiza trazados de elementos geométricos complejos.",
      "Corta planchas y fierro en tiras, con herramientas o soldadura.",
      "Ejecuta uniones soldadas en posición plana, horizontal, vertical y sobre cabeza.",
      "Regula o dirige la regulación de la máquina soldadora.",
      "Repara soldaduras defectuosas.",
      "Levanta y transporta elementos pesados.",
    ],
    lugares_trabajo: [
      "Realiza labores en el exterior e interior.",
      "Trabaja sobre plataformas, escalas y andamios.",
      "Circula por toda la obra, por escalas, pasarelas, etc., para desplazarse a su frente de trabajo.",
      "En altura, en el montaje de estructuras metálicas.",
    ],
    herramientas: [
      "Combo, martillo cincelador, huincha, escuadra, plomo, nivel.",
      "Alicate, tenazas, caimán, destornilladores.",
      "Limas, brocas, prensas, tornillos mecánicos.",
      "Esmeril angular, taladro, sierra axial.",
      "Máquina de soldar.",
      "Equipo de oxiacetileno.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "supervisor",
    cargo_name: "Supervisor",
    area: "Edificación",
    descripcion_puesto: "El Supervisor es el responsable de la supervisión general de un departamento o área de la obra, incluyendo la gestión de equipos, la capacitación de trabajadores, la evaluación del desempeño y la gestión de proyectos. En algunos casos, el supervisor puede ser también responsable de la planificación estratégica y la gestión de recursos humanos de un área específica, para lograr los resultados esperados en plazos, costos, medio ambientes, calidad y seguridad.",
    tareas: [
      "Planifica y controla el uso de materiales, herramientas, maquinaria y equipos de su especialidad.",
      "Supervisa en terreno las distintas faenas de su especialidad.",
      "Instruye al personal a su cargo en cómo realizar las distintas tareas.",
      "Identifica y controla riesgos en los frentes de trabajo.",
    ],
    lugares_trabajo: [
      "Circula en forma permanente por toda la obra.",
      "Sube y baja por escalas para desplazarse en los frentes de trabajo.",
      "En altura sobre andamios, plataformas, pasarelas o losas, en la supervisión de tareas de su especialidad.",
      "En trabajos nocturnos puede tener bajos niveles de iluminación.",
    ],
    herramientas: [
      "Debe conocer las distintas herramientas de su especialidad.",
      "Debe conocer el funcionamiento de los distintos equipos o maquinarias que se utilizan en su especialidad.",
    ],
    orden_aseo: [
      "Eliminar materiales obsoletos o que no se utilizan.",
      "Mantener las áreas de trabajo limpias.",
      "Mantener los pasillos de tránsito libres de obstáculos.",
      "Mantener las áreas delimitadas y señalizadas, destinar zonas de almacenamiento, en especial materiales combustibles e inflamables.",
      "Mantener un programa de limpieza y retiro de basura; incluir 5 minutos de limpieza antes y después de terminar la jornada.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
  {
    slug: "visitas",
    cargo_name: "Visitas",
    area: "Edificación",
    descripcion_puesto: "Es la persona externa del proyecto por parte de empresas colaboradoras, proveedores, oficina central de Sacyr, quien debe cumplir con los estándares de Sacyr Chile S.A. al momento de ingresar al proyecto.",
    tareas: [
      "Durante su estadía en nuestras instalaciones siempre estará acompañado por la persona que viene a visitar, designada por la empresa Sacyr Chile S.A. / H.P.C.",
      "El personal deberá ir provisto con los Elementos de Protección Personal (Casco de seguridad, geólogo, zapatos de seguridad, ropa manga larga), durante toda la visita, o solicitar E.P.P. de visita en caso de no contar con ellos.",
      "Está prohibido Fumar en sectores No habilitados.",
      "El personal que acceda al centro respetará en todo momento las protecciones colectivas, así como toda la señalización existente: Respetar vías de tránsito peatonal y vehicular, respetar señales de rigger y toda instrucción entregada por el señalero.",
      "Está prohibido apoyarse en barandas de seguridad y redes anticaídas.",
      "El personal que vaya a ejecutar un trabajo específico deberá presentarse en Dpto. de Prevención de riesgos para verificar si están autorizados y cumplen con sistema de ingreso al SST.",
      "En caso de emergencia deberá dirigirse al Punto de Encuentro y seguir las instrucciones del equipo de Emergencia o en su defecto del responsable que le acompañe.",
    ],
    lugares_trabajo: [
      "Áreas autorizadas del proyecto.",
      "Oficinas administrativas.",
    ],
    herramientas: [],
    orden_aseo: [
      "Recomendaciones de Salud en obra: Se recomienda el uso de mascarilla en caso de presentar síntomas que puedan ser atribuibles a Enfermedades Respiratorias (solicitar en la recepción).",
      "Se recomienda lavado de manos frecuente con agua y jabón.",
      "Cúbrase la boca y nariz con el antebrazo o use un pañuelo desechable cuando tosa o estornude.",
    ],
    preguntas: SACYR_IRL_PREGUNTAS,
  },
];

// Map from cargo_name patterns to form slugs (for auto-detection by role)
export const CARGO_TO_IRL_SLUG: Record<string, string> = {
  "administrador de contrato": "administrador_de_contrato",
  "ayudante": "ayudante",
  "ayudante de especialidades": "ayudante",
  "capataz": "capataz",
  "carpintero obra civiles": "carpintero_obra_civiles",
  "carpintero obras civiles": "carpintero_obra_civiles",
  "carpintero og": "carpintero_og",
  "carpintero obra gruesa": "carpintero_og",
  "carpintero terminaciones": "carpintero_terminaciones",
  "electricista": "electricista",
  "enfierrador": "enfierrador",
  "equipo de topografía": "equipo_de_topografia",
  "topógrafo": "equipo_de_topografia",
  "geomensor": "equipo_de_topografia",
  "guardia": "guardia",
  "guardia de seguridad": "guardia",
  "jefe de terreno": "jefe_de_terreno",
  "maestro de instalaciones": "maestro_de_instalaciones",
  "monitor de seguridad": "monitor_de_seguridad",
  "operador de maquinaria pesada": "operador_de_maquinaria_pesada",
  "operador maquinaria pesada": "operador_de_maquinaria_pesada",
  "operador gt": "operador_gt",
  "operador grúa torre": "operador_gt",
  // 9 nuevos
  "operador montacargas": "operador_montacargas",
  "operador de montacargas": "operador_montacargas",
  "personal de aseo": "personal_de_aseo",
  "auxiliar de aseo": "personal_de_aseo",
  "prevencionista de riesgos": "prevencionista_de_riesgos",
  "profesional": "profesional",
  "rigger - señalero": "rigger_señalero",
  "rigger": "rigger_señalero",
  "señalero": "rigger_señalero",
  "sanitario": "sanitario",
  "instalador sanitario": "sanitario",
  "soldador": "soldador",
  "supervisor": "supervisor",
  "visitas": "visitas",
};
